apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
type: Opaque
data:
  WEB_SECRET_KEY: REPLACE_ME123456
  WEB_DEBUG: "FALSE"
  WEB_DATABASE_URL: cG9zdGdyZXM6Ly9rOHNfdGVzdDpPd090QmVwOUZydXRAbXktcGctcG9zdGdyZXNxbC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvazhzX3Rlc3Q=
  WEB_ALLOWED_HOSTS: 127.0.0.1,localhost,sb.test
