apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
type: Opaque
data:
  SECRET_KEY: UkVQTEFDRV9NRTEyMzQ1Ngo=
  DEBUG: VFJVRQ==
  DATABASE_URL: cG9zdGdyZXM6Ly9rOHNfdGVzdDpPd090QmVwOUZydXRAbXktcGctcG9zdGdyZXNxbC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvazhzX3Rlc3Q=
  ALLOWED_HOSTS: MTI3LjAuMC4xLGxvY2FsaG9zdCxzYi50ZXN0
