apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: django-migrate
          image: bfcc/k8s-test-django
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate", "--no-input"]
          envFrom:
            - secretRef:
                name: web-secrets
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
          volumeMounts:
            - name: secretvolume
              mountPath: /root/.postgresql/root.crt
              subPath: root.crt
      volumes:
        - name: secretvolume
          secret:
            secretName: pg-root-cert

      restartPolicy: OnFailure
